In [5]:
import numpy as np

In [6]:
u = np.array([1, 2, 3, 4])

In [7]:
v = np.array([6, 7, 9, 5])

In [8]:
u + 2

array([3, 4, 5, 6])

In [9]:
u

array([1, 2, 3, 4])

In [10]:
u * v

array([ 6, 14, 27, 20])

In [11]:
u ** v

array([    1,   128, 19683,  1024])

In [12]:
v + 2

array([ 8,  9, 11,  7])

In [13]:
u

array([1, 2, 3, 4])

In [32]:
v

array([6, 7, 9, 5])

### Vector-Vector multiplication (Dot Product)

In [14]:
u

array([1, 2, 3, 4])

In [2]:
import numpy as np

In [15]:
u

array([1, 2, 3, 4])

In [18]:
v.shape[0]

4

In [29]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
        
    return result
        

In [30]:
vector_vector_multiplication(u, v)

np.float64(67.0)

In [33]:
u.dot(v)

np.int64(67)