### One-Dimensional Arrays

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [6]:
np.zeros(0)

array([], dtype=float64)

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [16]:
a = np.array([1, 3, 5, 6, 6, 14])

In [17]:
a

array([ 1,  3,  5,  6,  6, 14])

In [24]:
a[4] = 10

In [25]:
a

array([ 1,  3,  5,  6, 10, 14])

In [26]:
a[4]

np.int64(10)

In [28]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [35]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [2]:
import numpy as np

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [8]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
n[0, 1].item()

2

In [11]:
n[0,1] = 20

In [12]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [16]:
n[2]

array([7, 8, 9])

In [18]:
n[0] = [1, 1, 1]

In [19]:
n

array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
n[:, 1]

array([1, 5, 8])

In [26]:
n[:]

array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
n[:, 2] = [11, 44, 55]

In [28]:
n

array([[ 1,  1, 11],
       [ 4,  5, 44],
       [ 7,  8, 55]])

In [61]:
np.random.seed(42)
100 * np.random.rand(5, 2)

array([[37.45401188, 95.07143064],
       [73.19939418, 59.86584842],
       [15.60186404, 15.59945203],
       [ 5.80836122, 86.61761458],
       [60.11150117, 70.80725778]])

In [62]:
np.random.seed(42)
100 * np.random.randn(5, 2)

array([[ 49.6714153 , -13.82643012],
       [ 64.76885381, 152.30298564],
       [-23.41533747, -23.41369569],
       [157.92128155,  76.74347292],
       [-46.94743859,  54.25600436]])

In [60]:
np.random.seed(42)
np.random.randint(low=0, high=100, size=(5, 2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

In [65]:
a = np.arange(5)

In [66]:
a +10

array([10, 11, 12, 13, 14])

In [67]:
a - 10

array([-10,  -9,  -8,  -7,  -6])

In [68]:
a +10

array([10, 11, 12, 13, 14])

In [69]:
a / 10

array([0. , 0.1, 0.2, 0.3, 0.4])

In [70]:
a

array([0, 1, 2, 3, 4])

In [81]:
b = ((10 + (a * 2)) ** 2 / 100 - 1)

In [82]:
b

array([0.  , 0.44, 0.96, 1.56, 2.24])

In [83]:
a + b

array([0.  , 1.44, 2.96, 4.56, 6.24])

In [84]:
a * b

array([0.  , 0.44, 1.92, 4.68, 8.96])

In [85]:
a

array([0, 1, 2, 3, 4])

In [86]:
a >= 2

array([False, False,  True,  True,  True])

In [87]:
a > 2

array([False, False, False,  True,  True])

In [88]:
b

array([0.  , 0.44, 0.96, 1.56, 2.24])

In [89]:
a > b

array([False,  True,  True,  True,  True])

In [90]:
a = b

In [91]:
a

array([0.  , 0.44, 0.96, 1.56, 2.24])

In [92]:
b

array([0.  , 0.44, 0.96, 1.56, 2.24])

In [93]:
a = np.arange(5)

In [94]:
a

array([0, 1, 2, 3, 4])

In [95]:
a <= b

array([ True, False, False, False, False])

In [96]:
a

array([0, 1, 2, 3, 4])

In [97]:
b

array([0.  , 0.44, 0.96, 1.56, 2.24])

In [98]:
a[a>b]

array([1, 2, 3, 4])

In [99]:
a>b

array([False,  True,  True,  True,  True])

In [100]:
a

array([0, 1, 2, 3, 4])

In [101]:
a.min

<function ndarray.min(axis=None, out=None, **kwargs)>

In [102]:
a.min()

np.int64(0)

In [103]:
a.min().item()

0

In [104]:
a.max().item()

4

In [105]:
a.sum().item()

10

In [106]:
a.mean().item()

2.0

In [107]:
a.std().item()

1.4142135623730951

In [108]:
n

array([[ 1,  1, 11],
       [ 4,  5, 44],
       [ 7,  8, 55]])

In [109]:
n.sum().item()

136