### One-Dimensional Arrays

In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [6]:
np.zeros(0)

array([], dtype=float64)

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [16]:
a = np.array([1, 3, 5, 6, 6, 14])

In [17]:
a

array([ 1,  3,  5,  6,  6, 14])

In [24]:
a[4] = 10

In [25]:
a

array([ 1,  3,  5,  6, 10, 14])

In [26]:
a[4]

np.int64(10)

In [28]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [35]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])